gcp_project_id       = "wideops-support-3934126"
gcp_region           = "europe-central2"
vpc_name             = "CustomVPC"
subnet_name          = "CustomSubnet"
subnet_ip_cidr_range = "10.0.0.0/24"
lb_ip                = "LB-IP"